sonar.sourceEncoding=UTF-8
sonar.projectKey=sivaprasadreddy_feedback-hub
sonar.projectName=feedback-hub
sonar.organization=sivaprasadreddy-github
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
#sonar.exclusions=src/main/java/**/config/*.*,src/main/java/**/entities/*.*,src/main/java/**/models/*.*,src/main/java/**/exceptions/*.*,src/main/java/**/utils/*.*,src/main/java/**/*Application.*
sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*IT.java,**/*IntegrationTest.java
sonar.java.codeCoveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports
