name: feedback-hub
services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  
  mailpit:
    image: axllent/mailpit:v1.31
    ports:
      - "1025:1025"
      - "8025:8025"

  ollama:
    image: ollama/ollama:0.34.1
    container_name: ollama
    ports:
      - "11434:11434"
    entrypoint: [ "/entrypoint.sh" ]
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/entrypoint.sh:ro

  feedbackhub:
    image: sivaprasadreddy/feedbackhub
    container_name: feedbackhub
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EMAIL_HOST: mailpit
      EMAIL_PORT: 1025
      OLLAMA_URL: http://ollama:11434
      OLLAMA_MODEL: gemma3:270m
      BOOTUI_ENABLED: on
      BOOTUI_MCP_ENABLED: on
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mailpit
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
