apiVersion: v1
kind: Service
metadata:
  name: speakup-svc
spec:
  type: NodePort
  selector:
    app: speakup-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speakup-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speakup-pod
  template:
    metadata:
      labels:
        app: speakup-pod
    spec:
      containers:
        - name: speakup
          image: sivaprasadreddy/speakup
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: speakup-configmap
                  key: db_jdbc_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: speakup-secrets
                  key: db_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: speakup-secrets
                  key: db_password
            - name: EMAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: speakup-configmap
                  key: email_host
            - name: EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: speakup-configmap
                  key: email_port
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 240
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 240
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
