apiVersion: v1
kind: ConfigMap
metadata:
  name: feedbackhub-configmap
data:
  db_jdbc_url: "jdbc:postgresql://feedbackhub-postgres-svc:5432/postgres"
  email_host: "feedbackhub-mailpit-svc"
  email_port: "1025"
---
apiVersion: v1
kind: Secret
metadata:
  name: feedbackhub-secrets
type: Opaque
# DON'T DO THIS IN PRODUCTION
stringData:
  db_username: "postgres"
  db_password: "postgres"
