apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feedbackhub-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: feedbackhub-svc
                port:
                  number: 8080
