name: Build

on:
  push:
    branches: [ "release" ]
    paths-ignore:
      - "*.md"
      - ".gitignore"
      - ".gitattributes"
      - ".sdkmanrc"
      - "README.md"
      - "LICENSE"
      - "Taskfile.yml"
      - "renovate.json"
      - "docs/**"

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/feedbackhub

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: 25
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Maven Project Version
        id: project
        run: echo "version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

      - name: Build and Publish Docker Image
        env:
          MAVEN_PROJECT_VERSION: ${{ steps.project.outputs.version }}
        run: |
          ./mvnw spring-boot:build-image -DskipTests -DdockerImageName="$DOCKER_IMAGE_NAME:$MAVEN_PROJECT_VERSION"
          docker tag "$DOCKER_IMAGE_NAME:$MAVEN_PROJECT_VERSION" "$DOCKER_IMAGE_NAME:latest"
          docker push "$DOCKER_IMAGE_NAME:$MAVEN_PROJECT_VERSION"
          docker push "$DOCKER_IMAGE_NAME:latest"
